DROP TABLE IF EXISTS options CASCADE;
CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title_id INTEGER REFERENCES titles(id) ON DELETE CASCADE,
  choice VARCHAR(255) NOT NULL,
  description VARCHAR(255)
);
