DROP TABLE IF EXISTS choices CASCADE;
CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  option_id INTEGER REFERENCES options(id) ON DELETE CASCADE,
  title_id INTEGER REFERENCES titles(id) ON DELETE CASCADE,
  score SMALLINT NOT NULL
);
